apiVersion: v1
kind: Service
metadata:
  name: spotify-app-service
  labels:
    app: spotify-clone-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 3000
  selector:
    app: spotify-app